src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Column as Column;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $customer_id;

    // /**
    //  * @ORM\Column(type="integer")
    //  */
    // private $ammount;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $shipping_address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $order_address;

    /**
     * @ORM\Column(type="datetime")
     */
    private $order_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $order_status;
    
    /**
     * @ORM\Column(type="string")
     */
    private $price;

    /**
     * @ORM\OneToMany(targetEntity=OrderDetail::class, mappedBy="foundOrder",  fetch="EAGER")
     */
    private $orderDetails;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCustomerId(): ?int
    {
        return $this->customer_id;
    }

    public function setCustomerId(int $customer_id): self
    {
        $this->customer_id = $customer_id;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getShippingAddress(): ?string
    {
        return $this->shipping_address;
    }

    public function setShippingAddress(string $shipping_address): self
    {
        $this->shipping_address = $shipping_address;

        return $this;
    }

    public function getOrderAddress(): ?string
    {
        return $this->order_address;
    }

    public function setOrderAddress(string $order_address): self
    {
        $this->order_address = $order_address;

        return $this;
    }

    public function getOrderDate(): ?\DateTimeInterface
    {
        return $this->order_date;
    }

    public function setOrderDate(\DateTimeInterface $order_date): self
    {
        $this->order_date = $order_date;

        return $this;
    }

    public function getOrderStatus(): ?string
    {
        return $this->order_status;
    }

    public function setOrderStatus(string $order_status): self
    {
        $this->order_status = $order_status;

        return $this;
    }

    /**
     * @return Collection|OrderDetail[]
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(OrderDetail $orderDetail): self
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails[] = $orderDetail;
            $orderDetail->setFoundOrder($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetail $orderDetail): self
    {
        if ($this->orderDetails->contains($orderDetail)) {
            $this->orderDetails->removeElement($orderDetail);
            // set the owning side to null (unless already changed)
            if ($orderDetail->getFoundOrder() === $this) {
                $orderDetail->setFoundOrder(null);
            }
        }

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    public function __construct()
    {
        $this->created = new \DateTime();
        $this->OrderDetail = new ArrayCollection();
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image_url;

    /**
     * 
     * @ORM\Column(type="datetime", nullable=false)
     * @ORM\Version
     * @var \DateTime
     */
    protected $created = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(string $image_url): self
    {
        $this->image_url = $image_url;

        return $this;
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use App\Repository\ProductRepository;
use App\Entity\Order;
use App\Entity\OrderDetail;
use App\Repository\OrderDetailRepository;


class OrderController extends AbstractController
{
    protected $session;
    protected $productRepository;
    protected $orderDetailRepository;

    public function __construct(SessionInterface $session, ProductRepository $productRepository, OrderDetailRepository $orderDetailRepository) {
        $this->session = $session;
        $this->productRepository = $productRepository;
        $this->orderDetailRepository = $orderDetailRepository;
    }
    /**
     * @Route("/order", name="order")
     */
    public function index()
    {
        return $this->render('order/index.html.twig', [
            'controller_name' => 'OrderController',
        ]);
    }
    
    /**
     * @Route("/order/{orderId}", name="order_detail")
     */
    public function orderDetail($orderId)
    {
        $userId = $this->getUser()->getId();
        
        $order = $this->getDoctrine()
        ->getRepository(Order::class)
        ->findOneBy(array('customer_id' => $userId, 'id' => $orderId));
        // $order = $this->orderDetailRepository->findByOrderId($orderId);


        $order = $order->getOrderDetails();

        // dd($order);
        
        return $this->render('order/detail.html.twig', [
            'order' => $order,
        ]);
    }
}

templates/order/detail.html.twig
{% extends 'base.html.twig' %}

{% block content %}
<div class="order-detail">
<h3>Order information</h3>
  <div class="order-info">
    <p><span class="small-title">Shipping address:</span> {{order[0].foundOrder.shippingAddress}}</p>
    <p><span class="small-title">Billing address:</span> {{order[0].foundOrder.orderAddress}}</p>
    <p><span class="small-title">Order date:</span> {{order[0].foundOrder.orderDate|date('h:m d/m/yy')}}</p>
    <p><span class="small-title">Status:</span> {{order[0].foundOrder.orderStatus}}</p>
  </div>


  <h3>Ordered products</h3>
  <div class="order-detail-orders">
    {% for orderDetail in order %}
    <div class="orderDetails">
      <img src="{{ orderDetail.product.imageUrl }}">
      <div class="title">{{ orderDetail.product.name }}</div>
      <div>price: €{{ orderDetail.price }}</div>
      <div>Quantity: {{ orderDetail.quantity }}</div>
    </div>
    {% endfor %}
  </div>

</div>
{% endblock %}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello OrderController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/Yoram/Documents/Werk/symphony_webshop/symfony_webshop/src/Controller/OrderController.php'|file_link(0) }}">src/Controller/OrderController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/Yoram/Documents/Werk/symphony_webshop/symfony_webshop/templates/order/index.html.twig'|file_link(0) }}">templates/order/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}